export const NEW_BANNER_REQUEST = "NEW_BANNER_REQUEST";
export const NEW_BANNER_SUCCESS = "NEW_BANNER_SUCCESS";
export const NEW_BANNER_FAIL = "NEW_BANNER_FAIL";
export const NEW_BANNER_RESET = "NEW_BANNER_RESET";

export const ALL_BANNER_REQUEST = "ALL_BANNER_REQUEST";
export const ALL_BANNER_SUCCESS = "ALL_BANNER_SUCCESS";
export const ALL_BANNER_FAIL = "ALL_BANNER_FAIL";

export const SINGLE_BANNER_REQUEST = "SINGLE_BANNER_REQUEST";
export const SINGLE_BANNER_SUCCESS = "SINGLE_BANNER_SUCCESS";
export const SINGLE_BANNER_FAIL = "SINGLE_BANNER_FAIL";
export const SINGLE_BANNER_RESET = "SINGLE_BANNER_RESET";

export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";
export const DELETE_BANNER_RESET = "DELETE_BANNER_RESET";

export const UPDATE_BANNER_REQUEST = "UPDATE_BANNER_REQUEST";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAIL = "UPDATE_BANNER_FAIL";
export const UPDATE_BANNER_RESET = "UPDATE_BANNER_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";