export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEWS_REQUEST = "NEW_REVIEWS_REQUEST";
export const NEW_REVIEWS_SUCCESS = "NEW_REVIEWS_SUCCESS";
export const NEW_REVIEWS_FAIL = "NEW_REVIEWS_FAIL";
export const NEW_REVIEWS_RESET = "NEW_REVIEWS_RESET";



export const CLEAR_ERRORS = "CLEAR_ERRORS";